### ISSUE TITLE
Session 4's Students' Obbies

### ISSUE THREAD

**Issue by EthanThatOneKid** [codeninjasgg/roblox-royale-camp#1]
`Evan`: [Obby](https://web.roblox.com/games/5535013173/Obby)
`Airica`: [Obby](https://web.roblox.com/games/5535414744/Place-Number)
`Airlia`: [Obby](https://www.roblox.com/games/5535372366/Untitled-Game)

**Comment by codeninjasgg** [comment]
Updated Hall of Fame 👍

**Comment by codeninjasgg** [comment]
Updated Hall of Fame 👍
